---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
    stage: prod
spec:
  template:
    metadata:
      labels:
        networking.knative.dev/visibility: cluster-local
        stage: prod
      annotations:
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        # the minimum number of pods to scale down to
        autoscaling.knative.dev/minScale: "1"
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
        - name: payment
          # image: {{ .Values.image.repo }}/rs-payment:{{ .Values.image.version }}
          image: {{ .Values.image.alt_repo }}/rs-payment:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # agent networking access
          env:
          - name: CART_HOST
            value: {{ .Values.host.CART_HOST }}.{{ .Release.Namespace }}.svc.cluster.local
          - name: USER_HOST
            value: {{ .Values.host.USER_HOST }}.{{ .Release.Namespace }}.svc.cluster.local
          {{- if .Values.payment.gateway }}
          - name: PAYMENT_GATEWAY
            value: {{ .Values.payment.gateway }}
          {{- end }}
            # - name: INSTANA_AGENT_HOST
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: status.hostIP
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
