apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    service: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: web
        # image: {{ .Values.image.repo }}/rs-web:{{ .Values.image.version }}
        image: {{ .Values.image.alt_repo }}/rs-web:{{ .Values.image.version }}
        # imagePullPolicy: {{ .Values.image.pullPolicy }}
        imagePullPolicy: Always
        env:
        - name: CART_HOST
          value: {{ .Values.host.CART_HOST }}.{{ .Release.Namespace }}.svc.cluster.local
        - name: CATALOGUE_HOST
          value: {{ .Values.host.CATALOGUE_HOST }}.{{ .Release.Namespace }}.svc.cluster.local
        - name: RATINGS_HOST
          value: {{ .Values.host.RATINGS_HOST }}.{{ .Release.Namespace }}.svc.cluster.local
        {{- if .Values.eum.key }}
        - name: INSTANA_EUM_KEY
          value: {{ .Values.eum.key }}
        - name: INSTANA_EUM_REPORTING_URL
          value: {{ .Values.eum.url }}          
        {{- end}}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
